version: 2
project_name: cloudflare-dynamic-dns
before:
  hooks:
  - go mod tidy
builds:
- binary: cloudflare-dynamic-dns
  env:
  - CGO_ENABLED=0
  targets:
  - linux_amd64
  - linux_386
  - linux_arm64
  - linux_arm_6
  - linux_arm_7
  - linux_mips
  - linux_mipsle
  - linux_mips64
  - linux_mips64le
  - linux_riscv64
  - darwin_amd64
  - darwin_arm64
  - windows_amd64
  - windows_386
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE
  - README.md
  - systemd/*
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ incpatch .Version }}-next'
aurs:
- name: cloudflare-dynamic-dns-bin
  homepage: https://github.com/zebradil/cloudflare-dynamic-dns
  description: Dynamic DNS client for Cloudflare with IPv6/IPv4 support
  maintainers:
  - German Lashevich <german.lashevich@gmail.com>
  license: MIT
  private_key: '{{ .Env.AUR_SSH_KEY }}'
  git_url: ssh://aur@aur.archlinux.org/cloudflare-dynamic-dns-bin.git
  package: |-
    BIN=cloudflare-dynamic-dns

    install -Dm755 ./$BIN -t "${pkgdir}/usr/bin"
    install -Dm644 systemd/* -t "$pkgdir"/usr/lib/systemd/system
    install -m700 -d "$pkgdir"/etc/cloudflare-dynamic-dns/config.d

    # completions
    mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
    mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
    mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
    ./$BIN completion bash | install -Dm644 /dev/stdin "${pkgdir}/usr/share/bash-completion/completions/$BIN"
    ./$BIN completion fish | install -Dm644 /dev/stdin "${pkgdir}/usr/share/fish/vendor_completions.d/$BIN.fish"
    ./$BIN completion zsh  | install -Dm644 /dev/stdin "${pkgdir}/usr/share/zsh/site-functions/_$BIN"
  commit_author:
    name: Zebradil Bot
    email: german.lashevich+github-zebradil-bot@gmail.com
nfpms:
- vendor: Zebradil
  homepage: https://github.com/zebradil/cloudflare-dynamic-dns
  maintainer: German Lashevich <german.lashevich@gmail.com>
  description: Dynamic DNS client for Cloudflare with IPv6/IPv4 support
  license: MIT
  formats:
  - apk
  - deb
  - rpm
  contents:
  - src: systemd/
    dst: /usr/lib/systemd/system/
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-amd64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-amd64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-amd64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-amd64
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
- goos: linux
  goarch: arm64
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-arm64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-arm64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-arm64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-arm64
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64
- goos: linux
  goarch: arm
  goarm: "6"
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-arm-6
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-arm-6
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-arm-6
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-arm-6
  use: buildx
  build_flag_templates:
  - --platform=linux/arm/6
- goos: linux
  goarch: arm
  goarm: "7"
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-arm-7
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-arm-7
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-arm-7
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-arm-7
  use: buildx
  build_flag_templates:
  - --platform=linux/arm/7
- goos: linux
  goarch: riscv64
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-riscv64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-riscv64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-riscv64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-riscv64
  use: buildx
  build_flag_templates:
  - --platform=linux/riscv64
docker_manifests:
- name_template: ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-amd64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-arm64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-arm-6
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-arm-7
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Tag }}-linux-riscv64
- name_template: ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-amd64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-arm64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-arm-6
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-arm-7
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}-linux-riscv64
- name_template: ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-amd64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-arm64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-arm-6
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-arm-7
  - ghcr.io/zebradil/cloudflare-dynamic-dns:{{ .Major }}.{{ .Minor }}-linux-riscv64
- name_template: ghcr.io/zebradil/cloudflare-dynamic-dns:latest
  image_templates:
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-amd64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-arm64
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-arm-6
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-arm-7
  - ghcr.io/zebradil/cloudflare-dynamic-dns:latest-linux-riscv64
