apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: internal/execext
    lazy: true
    contents:
      - path: .
        git:
          url: https://github.com/go-task/task
          ref: 0941de3318ba2cd8e8611acc4e225b0bea5c817b
        includePaths:
          - internal/execext/*
        newRootPath: internal/execext
