---
name: PR Flow

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/flow-pr.yml'
      - '.github/workflows/job-lint.yml'
      - '.github/workflows/job-test.yml'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - '.goreleaser.yml'
      - 'cmd/**'

jobs:
  lint:
    uses: ./.github/workflows/job-lint.yml
  test:
    uses: ./.github/workflows/job-test.yml
  nix-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Try to update nix flake
        run: ./.github/scripts/update-flake-version pr-${{ github.event.pull_request.number }}
      - name: Print changes
        run: git diff
